# Библиотека `pandas`: часть 1

*Алла Тамбовцева*

## Домашнее задание 

### Описание домашнего задания и формат сдачи

В домашнем задании необходимо решить предложенные задачи по программированию – вписать свой код в ячейки после условий задач вместо комментария `### YOUR CODE HERE ###` в файле *homework-pandas1.ipynb* и сохранить изменения, используя опцию *Save and Checkpoint* из вкладки меню *File* или кнопку *Save and Checkpoint* на панели инструментов. Итоговый файл в формате `.ipynb` (файл Jupyter Notebook) необходимо загрузить в личный кабинет обучающей онлайн платформы Skillbox (https://go.skillbox.ru/) и отправить на проверку.

### Задание 1

Загрузить массив `NumPy` из файла `"arr_pandas.npy"` (как в задании к предыдущему модулю) и преобразовать его в датафрейм. Массив содержит данные по результатам соревнований Scottish Hill Races в 2000 году (полное описание на английском языке можно посмотреть на [странице](https://vincentarelbundock.github.io/Rdatasets/doc/DAAG/races2000.html) с документацией по исходному файлу с данными).

**Подсказка (преобразование в датафрейм):**

In [18]:
import pandas as pd
import numpy as np
arr = np.load('arr_pandas.npy', allow_pickle=True)
dat = pd.DataFrame(arr)  # arr - массив NumPy из файла
# Если при загрузке файла вы столкнетесь с ошибкой, в которой будет упомянут параметр allow_pickle=False
# То попробуйте явно задать значение этого параметра - allow_pickle=True при вызове функции загрузки файла

In [19]:
dat

                        0     1     2         3         4         5
0      Aonach Mor Gondola     2  2000  0.403611  0.518889    uphill
1       Broughton Brewery     2   650  0.254444  0.316667     other
2             El-Brim-Ick     3   750  0.485833  0.389167     other
3      The Devils Burdens    21  4100   2.39972   3.09333     relay
4           Tiso Carnethy     6  2500  0.782222  0.919167      hill
5                 Criffel     7  1800  0.793333   1.00333      hill
6              Chapelgill   1.5  1400  0.314444  0.376667      hill
7            Norman's Law     5   700  0.464167  0.609167      hill
8            Craig Dunain     6   900  0.546111  0.625833      hill
9             Knockfarrel     5  1200  0.623333  0.734167      hill
10                 Screel     4  1300  0.458889  0.543611      hill
11      O.P.S. Clachnaben  10.5  3500   1.27889   1.48778      hill
12            Hunters Bog   4.5   800  0.409444  0.477778     other
13         Aberfoyle Dash     3  1000    0.3375  0.381389    uphill
14          Manx Mountain  30.5  8000   4.46972   5.52333  marathon
15          Whangie Whizz   3.5   800  0.395556  0.464167      hill
16                Ben Rha   7.5   800  0.738056  0.997222     relay
17          Stuc A'Chroin    14  5000   1.98333   2.39889      hill
18            29th Dumyat     5  1250  0.552778  0.637778      hill
19             Ben Lomond     9  3192   1.03778   1.19917      hill
20               Kinnoull     4   800  0.387222    0.4525      hill
21               Goatfell     8  2866   1.22778   1.52639      hill
22  Scottish Nuclear Kaim   3.5  1250  0.431111      0.54      hill
23             Ardoch Rig     7   600  0.678889  0.837222      hill
24            Culter Fell    12  4000   1.72167   1.98778     other
25           Isle of Jura    16  7500   3.11639   3.83944     other
26                 Scolty     5   800  0.495833  0.579167      hill
27              Cornalees   5.5   800  0.618333       NaN      hill
28           12 Trig Trog    46  7500   8.30694   13.5478      hill
29            Kilpatricks     6  1400  0.739722  0.874167      hill
..                    ...   ...   ...       ...       ...       ...
47               Whiteash   5.5   728  0.508889  0.768333      hill
48       Meall Ant-Suidhe   3.5  1500     0.465  0.609722      hill
49         Half Ben Nevis     5  1200  0.794167   1.03083     other
50            Lochaber AC     2   900  0.284722  0.360556      hill
51      Lochaber Highland     2   900  0.294167  0.473056      hill
52              Mash Hill     6  2500  0.794167   1.05194      hill
53            Ben Rhinnes    14  4900   1.97611   2.35583      hill
54              Beinn Lee     7   500  0.716667  0.943333      hill
55             Creag Dubh     3  1223  0.463889  0.601667      hill
56             Glen Clova    15  5500   2.56722   2.96222      hill
57             Caerketton   2.5   800  0.208611  0.246667      hill
58               Wideford   5.5   741  0.563611  0.724167      hill
59            Tap O'North     6  1220  0.665833  0.817778      hill
60                Lomonds     9  2200   1.05306   1.29389      hill
61                   Oban  2.25   500  0.232222  0.298889      hill
62              Ben Nevis    10  4400   1.42611   1.72361      hill
63                Braemar     4  2000  0.407778       NaN     other
64        Moffat Beef Tub     2  1500  0.332222  0.436944      hill
65          Cairn William     6  1400  0.704444  0.809722      hill
66          Corrieyairick    16  2250   1.66472   1.96333      hill
67                 Morven     5  1700  0.609167  0.785833      hill
68                Merrick     8  2710   1.13333   1.39472      hill
69          Two Breweries    18  4900   2.56583   3.08833      hill
70            Manor Water    10  2300   1.18444    1.4975      hill
71               Pentland    16  6200   2.37778     2.785      hill
72                  Tinto   4.5  1500  0.499444  0.581111      hill
73             Druim Fada   6.5  1000  0.751111  0.972222     other
74                 Elrick   3.6   650  0.358056    0.4425     relay
75                Gondola   2.5  2000  0.387222  0.518889    uphill
76            Greenmantle     2   650  0.254444  0.316667     other

[77 rows x 6 columns]

### Задание 2

Определить, сколько в датафрейме строк и столбцов. Привести код и указать ответ в виде текста или комментария к коду.

In [23]:
dat.shape # 77 строк, 6 столбцов

(77, 6)

### Задание 3

Присвоить столбцам следующие названия (указаны с пояснениями): 

* `id`: id участника
* `dist`: расстояние в милях (по карте)
* `climb`: высота, достигнутая на маршруте (в сумме за весь маршрут, в футах)
* `time`: время (в часах)
* `timef`: время для женщин (в часах)
* `type`: тип гонки (*hill*, *marathon*, *relay*, *uphill* or *other*)

In [25]:
dat.columns = ['id', 'dist', 'climb', 'time', 'timef', 'type']
dat

                       id  dist climb      time     timef      type
0      Aonach Mor Gondola     2  2000  0.403611  0.518889    uphill
1       Broughton Brewery     2   650  0.254444  0.316667     other
2             El-Brim-Ick     3   750  0.485833  0.389167     other
3      The Devils Burdens    21  4100   2.39972   3.09333     relay
4           Tiso Carnethy     6  2500  0.782222  0.919167      hill
5                 Criffel     7  1800  0.793333   1.00333      hill
6              Chapelgill   1.5  1400  0.314444  0.376667      hill
7            Norman's Law     5   700  0.464167  0.609167      hill
8            Craig Dunain     6   900  0.546111  0.625833      hill
9             Knockfarrel     5  1200  0.623333  0.734167      hill
10                 Screel     4  1300  0.458889  0.543611      hill
11      O.P.S. Clachnaben  10.5  3500   1.27889   1.48778      hill
12            Hunters Bog   4.5   800  0.409444  0.477778     other
13         Aberfoyle Dash     3  1000    0.3375  0.381389    uphill
14          Manx Mountain  30.5  8000   4.46972   5.52333  marathon
15          Whangie Whizz   3.5   800  0.395556  0.464167      hill
16                Ben Rha   7.5   800  0.738056  0.997222     relay
17          Stuc A'Chroin    14  5000   1.98333   2.39889      hill
18            29th Dumyat     5  1250  0.552778  0.637778      hill
19             Ben Lomond     9  3192   1.03778   1.19917      hill
20               Kinnoull     4   800  0.387222    0.4525      hill
21               Goatfell     8  2866   1.22778   1.52639      hill
22  Scottish Nuclear Kaim   3.5  1250  0.431111      0.54      hill
23             Ardoch Rig     7   600  0.678889  0.837222      hill
24            Culter Fell    12  4000   1.72167   1.98778     other
25           Isle of Jura    16  7500   3.11639   3.83944     other
26                 Scolty     5   800  0.495833  0.579167      hill
27              Cornalees   5.5   800  0.618333       NaN      hill
28           12 Trig Trog    46  7500   8.30694   13.5478      hill
29            Kilpatricks     6  1400  0.739722  0.874167      hill
..                    ...   ...   ...       ...       ...       ...
47               Whiteash   5.5   728  0.508889  0.768333      hill
48       Meall Ant-Suidhe   3.5  1500     0.465  0.609722      hill
49         Half Ben Nevis     5  1200  0.794167   1.03083     other
50            Lochaber AC     2   900  0.284722  0.360556      hill
51      Lochaber Highland     2   900  0.294167  0.473056      hill
52              Mash Hill     6  2500  0.794167   1.05194      hill
53            Ben Rhinnes    14  4900   1.97611   2.35583      hill
54              Beinn Lee     7   500  0.716667  0.943333      hill
55             Creag Dubh     3  1223  0.463889  0.601667      hill
56             Glen Clova    15  5500   2.56722   2.96222      hill
57             Caerketton   2.5   800  0.208611  0.246667      hill
58               Wideford   5.5   741  0.563611  0.724167      hill
59            Tap O'North     6  1220  0.665833  0.817778      hill
60                Lomonds     9  2200   1.05306   1.29389      hill
61                   Oban  2.25   500  0.232222  0.298889      hill
62              Ben Nevis    10  4400   1.42611   1.72361      hill
63                Braemar     4  2000  0.407778       NaN     other
64        Moffat Beef Tub     2  1500  0.332222  0.436944      hill
65          Cairn William     6  1400  0.704444  0.809722      hill
66          Corrieyairick    16  2250   1.66472   1.96333      hill
67                 Morven     5  1700  0.609167  0.785833      hill
68                Merrick     8  2710   1.13333   1.39472      hill
69          Two Breweries    18  4900   2.56583   3.08833      hill
70            Manor Water    10  2300   1.18444    1.4975      hill
71               Pentland    16  6200   2.37778     2.785      hill
72                  Tinto   4.5  1500  0.499444  0.581111      hill
73             Druim Fada   6.5  1000  0.751111  0.972222     other
74                 Elrick   3.6   650  0.358056    0.4425     relay
75                Gondola   2.5  2000  0.387222  0.518889    uphill
76            Greenmantle     2   650  0.254444  0.316667     other

[77 rows x 6 columns]

### Задание 4

Вывести на экран значение высоты, достигнутой на маршруте участником *Norman's Law*.

In [44]:
print(dat.iloc[7, 2])
dat.index = dat.id
dat.loc["Norman's Law", 'climb']

700

700

### Задание 5
Вывести на экран значения показателей `dist`, `climb` , `time` для первых 10 участников.

In [63]:
dat[['dist', 'climb', 'time']][:10]

                   dist climb      time
id
Aonach Mor Gondola    2  2000  0.403611
Broughton Brewery     2   650  0.254444
El-Brim-Ick           3   750  0.485833
The Devils Burdens   21  4100   2.39972
Tiso Carnethy         6  2500  0.782222
Criffel               7  1800  0.793333
Chapelgill          1.5  1400  0.314444
Norman's Law          5   700  0.464167
Craig Dunain          6   900  0.546111
Knockfarrel           5  1200  0.623333

### Задание 6

Вывести на экран сводную информацию по датафрейму, которая включает типы всех столбцов. Сколько столбцов типа `float` в датафрейме? Привести ответ на вопрос в виде текста или комментария к коду.

In [66]:
dat.info() # 0 объектов типа float

<class 'pandas.core.frame.DataFrame'>
Index: 77 entries, Aonach Mor Gondola to Greenmantle
Data columns (total 6 columns):
id       77 non-null object
dist     77 non-null object
climb    77 non-null object
time     77 non-null object
timef    75 non-null object
type     77 non-null object
dtypes: object(6)
memory usage: 6.7+ KB

### Задание 7

Выбрать строки, которые соответствуют участникам эстафеты (*relay*).

In [71]:
dat[dat['type']=='relay']

                                    id dist climb      time     timef   type
id
The Devils Burdens  The Devils Burdens   21  4100   2.39972   3.09333  relay
Ben Rha                        Ben Rha  7.5   800  0.738056  0.997222  relay
Elrick                          Elrick  3.6   650  0.358056    0.4425  relay

### Задание 8

Выбрать строки, которые соответствуют участникам гонки в холмах (*hill*), которые в сумме достигли высоты более 1000 футов. Посчитать, сколько таких участников.

In [75]:
dat[(dat['type']=='hill') & (dat['climb'] > 1000)].shape[0]

39

### Задание 9

Выбрать строки, соответствующие участникам, которые либо достигли высоты более 4000 футов, либо потратили менее 0.5 часов.

In [76]:
dat[(dat['climb'] > 4000) | (dat['time'] < 0.5)]

,id,dist,climb,time,timef,type
id,,,,,,
Aonach Mor Gondola,Aonach Mor Gondola,2,2000,0.403611,0.518889,uphill
Broughton Brewery,Broughton Brewery,2,650,0.254444,0.316667,other
El-Brim-Ick,El-Brim-Ick,3,750,0.485833,0.389167,other
The Devils Burdens,The Devils Burdens,21,4100,2.39972,3.09333,relay
Chapelgill,Chapelgill,1.5,1400,0.314444,0.376667,hill
Norman's Law,Norman's Law,5,700,0.464167,0.609167,hill
Screel,Screel,4,1300,0.458889,0.543611,hill
Hunters Bog,Hunters Bog,4.5,800,0.409444,0.477778,other
Aberfoyle Dash,Aberfoyle Dash,3,1000,0.3375,0.381389,uphill
Manx Mountain,Manx Mountain,30.5,8000,4.46972,5.52333,marathon
Whangie Whizz,Whangie Whizz,3.5,800,0.395556,0.464167,hill
Stuc A'Chroin,Stuc A'Chroin,14,5000,1.98333,2.39889,hill
Kinnoull,Kinnoull,4,800,0.387222,0.4525,hill
Scottish Nuclear Kaim,Scottish Nuclear Kaim,3.5,1250,0.431111,0.54,hill
Isle of Jura,Isle of Jura,16,7500,3.11639,3.83944,other
Scolty,Scolty,5,800,0.495833,0.579167,hill
12 Trig Trog,12 Trig Trog,46,7500,8.30694,13.5478,hill
Ben Sheann,Ben Sheann,2.5,1400,0.381667,0.484722,hill
Glen Rosa,Glen Rosa,13,5500,2.22028,2.70472,hill
West Highland Way,West Highland Way,95,9200,15.4389,18.8792,other
Eildon Two,Eildon Two,4.5,1500,0.427222,0.507778,other
Black Hill,Black Hill,4,600,0.447778,0.532222,hill
Meall Ant-Suidhe,Meall Ant-Suidhe,3.5,1500,0.465,0.609722,hill
Lochaber AC,Lochaber AC,2,900,0.284722,0.360556,hill
Lochaber Highland,Lochaber Highland,2,900,0.294167,0.473056,hill
Ben Rhinnes,Ben Rhinnes,14,4900,1.97611,2.35583,hill
Creag Dubh,Creag Dubh,3,1223,0.463889,0.601667,hill
Glen Clova,Glen Clova,15,5500,2.56722,2.96222,hill
Caerketton,Caerketton,2.5,800,0.208611,0.246667,hill
Oban,Oban,2.25,500,0.232222,0.298889,hill
Ben Nevis,Ben Nevis,10,4400,1.42611,1.72361,hill
Braemar,Braemar,4,2000,0.407778,NaN,other
Moffat Beef Tub,Moffat Beef Tub,2,1500,0.332222,0.436944,hill
Two Breweries,Two Breweries,18,4900,2.56583,3.08833,hill
Pentland,Pentland,16,6200,2.37778,2.785,hill
Tinto,Tinto,4.5,1500,0.499444,0.581111,hill
Elrick,Elrick,3.6,650,0.358056,0.4425,relay
Gondola,Gondola,2.5,2000,0.387222,0.518889,uphill
Greenmantle,Greenmantle,2,650,0.254444,0.316667,other

### Задание 10

Создать столбец `time_min`, который содержит время маршрута, измеренное в минутах.

In [77]:
dat['time_min'] = dat['time'] * 60
dat

,id,dist,climb,time,timef,type,time_min
id,,,,,,,
Aonach Mor Gondola,Aonach Mor Gondola,2,2000,0.403611,0.518889,uphill,24.2167
Broughton Brewery,Broughton Brewery,2,650,0.254444,0.316667,other,15.2667
El-Brim-Ick,El-Brim-Ick,3,750,0.485833,0.389167,other,29.15
The Devils Burdens,The Devils Burdens,21,4100,2.39972,3.09333,relay,143.983
Tiso Carnethy,Tiso Carnethy,6,2500,0.782222,0.919167,hill,46.9333
Criffel,Criffel,7,1800,0.793333,1.00333,hill,47.6
Chapelgill,Chapelgill,1.5,1400,0.314444,0.376667,hill,18.8667
Norman's Law,Norman's Law,5,700,0.464167,0.609167,hill,27.85
Craig Dunain,Craig Dunain,6,900,0.546111,0.625833,hill,32.7667
Knockfarrel,Knockfarrel,5,1200,0.623333,0.734167,hill,37.4
Screel,Screel,4,1300,0.458889,0.543611,hill,27.5333
O.P.S. Clachnaben,O.P.S. Clachnaben,10.5,3500,1.27889,1.48778,hill,76.7333
Hunters Bog,Hunters Bog,4.5,800,0.409444,0.477778,other,24.5667
Aberfoyle Dash,Aberfoyle Dash,3,1000,0.3375,0.381389,uphill,20.25
Manx Mountain,Manx Mountain,30.5,8000,4.46972,5.52333,marathon,268.183
Whangie Whizz,Whangie Whizz,3.5,800,0.395556,0.464167,hill,23.7333
Ben Rha,Ben Rha,7.5,800,0.738056,0.997222,relay,44.2833
Stuc A'Chroin,Stuc A'Chroin,14,5000,1.98333,2.39889,hill,119
29th Dumyat,29th Dumyat,5,1250,0.552778,0.637778,hill,33.1667
Ben Lomond,Ben Lomond,9,3192,1.03778,1.19917,hill,62.2667
Kinnoull,Kinnoull,4,800,0.387222,0.4525,hill,23.2333
Goatfell,Goatfell,8,2866,1.22778,1.52639,hill,73.6667
Scottish Nuclear Kaim,Scottish Nuclear Kaim,3.5,1250,0.431111,0.54,hill,25.8667
Ardoch Rig,Ardoch Rig,7,600,0.678889,0.837222,hill,40.7333
Culter Fell,Culter Fell,12,4000,1.72167,1.98778,other,103.3
Isle of Jura,Isle of Jura,16,7500,3.11639,3.83944,other,186.983
Scolty,Scolty,5,800,0.495833,0.579167,hill,29.75
Cornalees,Cornalees,5.5,800,0.618333,NaN,hill,37.1
12 Trig Trog,12 Trig Trog,46,7500,8.30694,13.5478,hill,498.417
Kilpatricks,Kilpatricks,6,1400,0.739722,0.874167,hill,44.3833
...,...,...,...,...,...,...,...
Whiteash,Whiteash,5.5,728,0.508889,0.768333,hill,30.5333
Meall Ant-Suidhe,Meall Ant-Suidhe,3.5,1500,0.465,0.609722,hill,27.9
Half Ben Nevis,Half Ben Nevis,5,1200,0.794167,1.03083,other,47.65
Lochaber AC,Lochaber AC,2,900,0.284722,0.360556,hill,17.0833
Lochaber Highland,Lochaber Highland,2,900,0.294167,0.473056,hill,17.65
Mash Hill,Mash Hill,6,2500,0.794167,1.05194,hill,47.65
Ben Rhinnes,Ben Rhinnes,14,4900,1.97611,2.35583,hill,118.567
Beinn Lee,Beinn Lee,7,500,0.716667,0.943333,hill,43
Creag Dubh,Creag Dubh,3,1223,0.463889,0.601667,hill,27.8333
Glen Clova,Glen Clova,15,5500,2.56722,2.96222,hill,154.033
Caerketton,Caerketton,2.5,800,0.208611,0.246667,hill,12.5167
Wideford,Wideford,5.5,741,0.563611,0.724167,hill,33.8167
Tap O'North,Tap O'North,6,1220,0.665833,0.817778,hill,39.95
Lomonds,Lomonds,9,2200,1.05306,1.29389,hill,63.1833
Oban,Oban,2.25,500,0.232222,0.298889,hill,13.9333
Ben Nevis,Ben Nevis,10,4400,1.42611,1.72361,hill,85.5667
Braemar,Braemar,4,2000,0.407778,NaN,other,24.4667
Moffat Beef Tub,Moffat Beef Tub,2,1500,0.332222,0.436944,hill,19.9333
Cairn William,Cairn William,6,1400,0.704444,0.809722,hill,42.2667
Corrieyairick,Corrieyairick,16,2250,1.66472,1.96333,hill,99.8833
Morven,Morven,5,1700,0.609167,0.785833,hill,36.55
Merrick,Merrick,8,2710,1.13333,1.39472,hill,68
Two Breweries,Two Breweries,18,4900,2.56583,3.08833,hill,153.95
Manor Water,Manor Water,10,2300,1.18444,1.4975,hill,71.0667
Pentland,Pentland,16,6200,2.37778,2.785,hill,142.667
Tinto,Tinto,4.5,1500,0.499444,0.581111,hill,29.9667
Druim Fada,Druim Fada,6.5,1000,0.751111,0.972222,other,45.0667
Elrick,Elrick,3.6,650,0.358056,0.4425,relay,21.4833
Gondola,Gondola,2.5,2000,0.387222,0.518889,uphill,23.2333
Greenmantle,Greenmantle,2,650,0.254444,0.316667,other,15.2667

### Задание 11

Создать столбец `year` с годом соревнований (везде 2000 год). Внимание: столбец с годом должен быть числовым (целочисленным).

In [81]:
dat['year'] = int(2000)
dat.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77 entries, Aonach Mor Gondola to Greenmantle
Data columns (total 8 columns):
id          77 non-null object
dist        77 non-null object
climb       77 non-null object
time        77 non-null object
timef       75 non-null object
type        77 non-null object
time_min    77 non-null object
year        77 non-null int64
dtypes: int64(1), object(7)
memory usage: 7.9+ KB

.<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> 
# Дополнительное (необязательное) задание.
<br>

### Задание 1

Загрузить датафрейм из файла `extraversion.csv`, используя код ниже. При этом файл `extraversion.csv` должен находиться в той же папке, что и ноутбук с решениями. Его можно поместить в ту же папку, нажав кнопку *Upload* в *Home*.

In [85]:
# кодировка UTF-8, чтобы кириллица корректно считывалась на Windows
ps = pd.read_csv("extraversion.csv", encoding = "UTF-8")

Файл содержит результаты учебного психометрического исследования, целью которого является выявление связи между уровнем экстраверсии человека и его склонности к участию в волонтёрской деятельности. Датафрейм содержит следующие столбцы:

* `sex`: пол респондента (Женский, Мужской);
* `volunteer`: регулярное участие в волонтёрской деятельности (Да, Нет);
* `Q 1` - `Q 57`: ответы на вопросы по анкете Айзенка (Да, Нет), информацию об анкете и сами вопросы можно найти на [этой](http://ipp.hse.ru/57-testytest-ajzenka-ekstraversiya-introversiya-nejrotizm) странице.

In [2]:
import pandas as pd
import numpy as np
ps = pd.read_csv("extraversion.csv", encoding = "UTF-8")
#ps

### Задание 2

Определить, сколько в датафрейме строк и столбцов. Привести код и указать ответ в виде текста или комментария к коду.

In [3]:
ps.shape # 52 строки, 61 столбец

(52, 61)

### Задание 3

Переименовать столбцы `Q 1`-`Q 57` в `Q1`-`Q57`, другими словами, убрать в названиях всех столбцов пробелы в середине (если есть). 

**Подсказка 1:** Метод `.replace()` для строк на [pythontutor.ru](https://pythontutor.ru/lessons/str/).

**Подсказка 2:** Для выполнения этого задания можно написать функцию, которая будет заменять пробелы на «пустоту», а потом применить её с помощью функции `map()` ко всем элементам списка. Пример ниже иллюстрирует применение функции для изменения регистра текста.

In [ ]:
# Пример

L = ['яблоко', 'груша', 'слива']  # исходный список

# функция принимает на вход строку x и возвращает её же, 
# но большими буквами – метод .upper()

def f(x):
    """
    Input: x is a string.
    Output: x is a string.
    Makes all letters uppercase. 
    """
    return x.upper()

# результат: применяем функцию f к списку L через map и преобразуем в список
# можно убрать list() вначале и убедиться, что он здесь нужен

list(map(f, L))

['ЯБЛОКО', 'ГРУША', 'СЛИВА']

In [4]:
ps.columns = list(ps.columns[:4]) + list(ps.columns[4:].str.replace(' ',''))
ps.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'sex', 'volunteer', 'Q1', 'Q2', 'Q3',
       'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14',
       'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20', 'Q21', 'Q22', 'Q23', 'Q24',
       'Q25', 'Q26', 'Q27', 'Q28', 'Q29', 'Q30', 'Q31', 'Q32', 'Q33', 'Q34',
       'Q35', 'Q36', 'Q37', 'Q38', 'Q39', 'Q40', 'Q41', 'Q42', 'Q43', 'Q44',
       'Q45', 'Q46', 'Q47', 'Q48', 'Q49', 'Q50', 'Q51', 'Q52', 'Q53', 'Q54',
       'Q55', 'Q56', 'Q57'],
      dtype='object')

### Задание 4

Выбрать столбцы `Q1`, `Q3`, `Q8`, `Q10`, `Q13`, `Q17`, `Q22`, `Q25`, `Q27`, `Q39`, `Q44`, `Q46`, `Q49`, `Q53`, `Q56` и сохранить их в отдельный датафрейм `extra_yes`. 

Выбрать столбцы `Q5`, `Q15`, `Q20`, `Q29`, `Q32`, `Q34`, `Q37`,`Q41`, `Q51` и сохранить их в отдельный датафрейм `extra_no`.

Эти столбцы будут использоваться для вычисления индекса экстраверсии.

In [5]:
extra_yes = pd.DataFrame()
extra_yes = ps[['Q1', 'Q2', 'Q8', 'Q10', 'Q13', 'Q17', 'Q22', 'Q25', 'Q27', 'Q39', 'Q44', 'Q46', 'Q49', 'Q53', 'Q56']]
extra_no = ps[['Q5', 'Q15', 'Q20', 'Q29', 'Q32', 'Q34', 'Q37', 'Q41', 'Q51']]

### Задание 5

Посчитать для каждой строки в датафрейме `extra_yes` число ответов `"Да"` и полученный результат сохранить в переменную `extra_yes_sum`. Посчитать для каждой строки в датафрейме `extra_no` число ответов `"Нет"` и полученный результат сохранить в переменную `extra_no_sum`.

**Подсказка 1:** метод `.isin()` для [датафреймов](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html) `pandas`.

**Подсказка 2:** метод `.sum()` для [датафреймов](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sum.html) `pandas`.

In [6]:
extra_yes.loc[:,'extra_yes_sum'] = extra_yes.isin(['Да']).sum(axis = 1)
extra_no.loc[:,'extra_no_sum'] = extra_no.isin(['Нет']).sum(axis = 1)
extra_yes.head(5)
# extra_yes
# extra_no

C:\Users\Ivan\Anaconda3\lib\site-packages\pandas\core\indexing.py:362: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\Ivan\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

,Q1,Q2,Q8,Q10,Q13,Q17,Q22,Q25,Q27,Q39,Q44,Q46,Q49,Q53,Q56,extra_yes_sum
0,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,Нет,3
1,Да,Да,Да,Да,Нет,Да,Нет,Да,Да,Да,Нет,Нет,Да,Да,Да,11
2,Да,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Да,Да,Нет,Да,Нет,Да,9
3,Да,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Нет,Нет,Нет,Нет,Нет,Нет,3
4,Да,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет,Нет,Да,Да,Да,Да,10

### Задание 6

Добавить в исходный датафрейм столбец `extra`, который представляет собой индекс экстраверсии, который считается так: сумма числа ответов "Да" в `extra_yes` и числа ответов "Нет" в `extra_no`.

In [7]:
ps['extra'] = extra_yes['extra_yes_sum'] + extra_no['extra_no_sum']
ps['extra'].astype('int64')

0      5
1     17
2     14
3      5
4     14
5     18
6     15
7     21
8     13
9     20
10     9
11    18
12    15
13    17
14     6
15    15
16    15
17    15
18    12
19     8
20    12
21    11
22    17
23    18
24     7
25     4
26    13
27    13
28    13
29     3
30    14
31    12
32     5
33    10
34     9
35     6
36    16
37     8
38    10
39    15
40    13
41    14
42     7
43    11
44     7
45    15
46    10
47     2
48    19
49     9
50    14
51    12
Name: extra, dtype: int64

### Задание 7

Добавить в исходный датафрейм столбец `female`, состоящий из значений 0 и 1 (0 — Мужской, 1 — Женский). 

**Подсказка:** возможно, пригодится метод `.astype()` для [Series](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.Series.astype.html) в `pandas`, он преобразует типы столбцов.

In [17]:
ps['female'] =[0 if x == 'Мужской' else 1 for x in ps['sex'] ]
ps.head(15)

,Unnamed: 0,Unnamed: 0.1,sex,volunteer,Q1,Q2,Q3,Q4,Q5,Q6,...,Q50,Q51,Q52,Q53,Q54,Q55,Q56,Q57,extra,female
0,0,1,Женский,Нет,Да,Нет,Нет,Да,Да,Да,...,Нет,Да,Да,Нет,Нет,Нет,Нет,Да,5,1
1,1,2,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Нет,Да,Нет,Да,Да,Нет,17,1
2,2,3,Женский,Да,Да,Да,Нет,Нет,Да,Да,...,Нет,Нет,Да,Нет,Нет,Да,Да,Нет,14,1
3,3,4,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Да,Да,Нет,Нет,Нет,Да,Нет,Нет,5,1
4,4,5,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Да,Да,Нет,14,1
5,5,6,Женский,Нет,Да,Нет,Да,Да,Нет,Нет,...,Нет,Нет,Нет,Да,Да,Нет,Да,Нет,18,1
6,6,7,Женский,Нет,Да,Нет,Нет,Да,Да,Нет,...,Нет,Нет,Да,Да,Да,Да,Нет,Нет,15,1
7,7,8,Женский,Да,Да,Да,Да,Нет,Да,Да,...,Да,Нет,Да,Да,Да,Да,Да,Нет,21,1
8,8,9,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Нет,Да,Да,Нет,13,1
9,9,10,Женский,Да,Да,Да,Нет,Нет,Да,Нет,...,Нет,Нет,Нет,Да,Да,Да,Да,Нет,20,1
10,10,11,Мужской,Нет,Нет,Да,Нет,Нет,Да,Да,...,Нет,Да,Нет,Да,Да,Да,Да,Нет,9,0
11,11,12,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Да,Да,Нет,18,1
12,12,13,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Нет,Да,Да,Да,Да,15,1
13,13,14,Женский,Нет,Да,Да,Нет,Да,Да,Нет,...,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет,17,1
14,14,15,Женский,Нет,Нет,Нет,Нет,Да,Да,Нет,...,Да,Да,Да,Нет,Да,Да,Нет,Нет,6,1

### Задание 8

Выбрать из исходного датафрейма строки, которые соответствуют либо волонтёрам с индексом экстраверсии выше 15, либо не-волонтёрам с индексом экстраверсии ниже 15. Сохранить в датафрейм `pure`.

In [20]:
pure = pd.DataFrame(ps[((ps['volunteer']=='Да') & (ps['extra'] > 15)) | ((ps['volunteer']=='Нет') & (ps['extra'] < 15))])
pure.head(15)

,Unnamed: 0,Unnamed: 0.1,sex,volunteer,Q1,Q2,Q3,Q4,Q5,Q6,...,Q50,Q51,Q52,Q53,Q54,Q55,Q56,Q57,extra,female
0,0,1,Женский,Нет,Да,Нет,Нет,Да,Да,Да,...,Нет,Да,Да,Нет,Нет,Нет,Нет,Да,5,1
1,1,2,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Нет,Да,Нет,Да,Да,Нет,17,1
3,3,4,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Да,Да,Нет,Нет,Нет,Да,Нет,Нет,5,1
4,4,5,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Да,Да,Нет,14,1
7,7,8,Женский,Да,Да,Да,Да,Нет,Да,Да,...,Да,Нет,Да,Да,Да,Да,Да,Нет,21,1
8,8,9,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Нет,Да,Да,Нет,13,1
9,9,10,Женский,Да,Да,Да,Нет,Нет,Да,Нет,...,Нет,Нет,Нет,Да,Да,Да,Да,Нет,20,1
10,10,11,Мужской,Нет,Нет,Да,Нет,Нет,Да,Да,...,Нет,Да,Нет,Да,Да,Да,Да,Нет,9,0
11,11,12,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Да,Да,Нет,18,1
14,14,15,Женский,Нет,Нет,Нет,Нет,Да,Да,Нет,...,Да,Да,Да,Нет,Да,Да,Нет,Нет,6,1
18,18,19,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Нет,Да,Да,Нет,Да,12,1
19,19,20,Женский,Нет,Нет,Нет,Да,Да,Да,Нет,...,Да,Да,Да,Нет,Да,Нет,Да,Да,8,1
20,20,21,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Да,Да,Нет,Да,Да,Да,Нет,12,1
23,23,24,Мужской,Да,Да,Да,Нет,Нет,Да,Да,...,Нет,Нет,Да,Да,Нет,Да,Да,Нет,18,0
26,26,27,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Да,Да,Да,Да,Нет,Да,Нет,Нет,13,1

### Задание 9

Определить (любым способом, кроме явного подсчёта), сколько волонтёров и не-волонтёров в датафрейме `pure`.

In [9]:
vol = pure['volunteer'].isin(['Да']).sum()
non_vol = pure['volunteer'].isin(['Нет']).sum()
vol, non_vol

(6, 19)

### Задание 10

Определить минимальное, максимальное, среднее и медианное значение индекса экстраверсии в датафрейме `pure`. Сохранить полученные результаты в отдельные переменные (их должно быть 4).

Добавить в датафрейм `pure` столбец `high`, состоящий из 0 и 1, где 1 соответствует респондентам, уровень экстраверсии которых выше значения $m = \max\{\text{median}, \text{mean}\}$, то есть максимума из медианного и среднего значения, а 0 — респондентам с уровнем экстраверсии не выше $m$.

In [22]:
min_extra = pure['extra'].min()
max_extra = pure['extra'].max()
mean_extra = pure['extra'].mean()
median_extra = pure['extra'].median()
m = max(median_extra, mean_extra)

pure.loc[:,'high'] = [1 if x > m else 0 for x in pure.loc[:,'extra']]

pure.head()

,Unnamed: 0,Unnamed: 0.1,sex,volunteer,Q1,Q2,Q3,Q4,Q5,Q6,...,Q51,Q52,Q53,Q54,Q55,Q56,Q57,extra,female,high
0,0,1,Женский,Нет,Да,Нет,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Нет,Да,5,1,0
1,1,2,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Нет,Да,Да,Нет,17,1,1
3,3,4,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Нет,5,1,0
4,4,5,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Да,Да,Да,Да,Да,Нет,14,1,1
7,7,8,Женский,Да,Да,Да,Да,Нет,Да,Да,...,Нет,Да,Да,Да,Да,Да,Нет,21,1,1